project:
  type: website
  output-dir: docs


# book:
#   title: "MTH202 :: Fall 2025"
#   author: "Chris Hallstrom"
#   chapters:
#     - index.qmd
#     - intro.qmd
#     - summary.qmd
#     - references.qmd

 
 
website:
  title: "mth202 :: Calculus II <br>Fall 2025"
  description: "MTH202, Fall 2025"

  page-navigation: true
  
  navbar:
    background: "#7A85C1"

  sidebar:
    background: "#B2B0E8"
#    logo: "images/logo.png"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 1

    contents:
      - href: index.qmd
        text: Welcome
      - href: general.qmd
        text: General Info
      - href: support.qmd
      - href: content.qmd
        text: Course Content
      - href: structure.qmd
      - href: grades.qmd
      - href: UPElements.qmd
        text: University Policies


format:
  html:
    #theme: sandstone
    theme: simplex
    css: style/mth202.scss
    toc: true
    highlight-style: monokai

      
editor: visual

  