project:
  type: book
  output-dir: docs

book:
  title: "MTH 202 :: Calculus II"
  subtitle: "Fall 2025"
  
  page-navigation: true
  downloads: [pdf]
  
  navbar:
    background: "#7A85C1"
    search: true
    right:
      - href: general.qmd
        text: General Course Info
    downloads: [pdf]
  
  sidebar:
    background: "#B2B0E8"
    pinned: true
    align: center

    style: docked
    search: true
    collapse-level: 2

  chapters:
    - href: index.qmd
      text: Welcome
    - href: general.qmd
      text: General Info
    - href: support.qmd
    - href: content.qmd
      text: Course Content
    - href: structure.qmd
    - href: grades.qmd
    - href: UPElements.qmd
      text: University Policies
    

format:
  html:
    #theme: sandstone
    theme: simplex
    css: style/mth202.scss
    toc: true
    number-sections: false
    highlight-style: monokai
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    documentclass: memoir
    margin-left: 30mm
    margin-right: 30mm
    toc: true
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex
    include-in-header:  
        - text: |
            \usepackage{enumitem}

   
      
editor: visual

  