---
title: "Learning Targets"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
---

Broadly speaking, this course covers many of the foundational topics of **integral calculus**, meaning we will learn methods of evaluating integrals as well as interpret the integral in the context of a variety of applications. We will also introduce topics such as differential equations and Taylor series which are important tools as you build on your understaning of calculus in later courses.

The bulk of the course content is represented by the following specific topics which we will call **Learning Targets**. Your goal over the course of the semester is to demonstrate your understanding of these topics via various assessment tasks -- primarily our weekly check-ins. I've organized these topics to generally align with our textbook.

### Preliminary

**P1.** I can do three key things from first semester calculus: (a) sketch the derivative function, given a function's graph; (b) apply the chain rule to find the derivative of a composite function; and (c) apply the First Fundamental Theorem of Calculus to evaluate a definite integral.

### Evaluating Integrals

**I1.** Given the graph of a function and other data, I can construct an accurate graph of the antiderivative of the function by determining select values of the antiderivative as well as where the antiderivative is increasing/decreasing and CCU/CCD.

**I2.** I can apply the Second Fundamental Theorem of Calculus to find the antiderivative of a function in terms of an integral and also use the 2nd FTC to differentiate an integral function.

**I3.** I can use integration by substitution and integration by parts to evaluate integrals.

**I4.** I can apply an appropriate technique to evaluate or approximate a definite integral.

**I5.** I can determine whether improper integrals converge and evaluate them if they do.

### Using Definite Integrals

**A1.** I can use definite integrals to find the area between two curves.

**A2.\*** I can use definite integrals to find the arc length of a curve.

**A3.** I can use definite integrals to find the volume of a solid of revolution.

**A4.\*** I can use definite integrals to find the mass and center of mass of an object.

**A5.\*** I can use definite integrals to represent key quantities in physical applications such as work or pressure.

### Differential Equations

**D1.** I can check whether a function is a solution to a differential equation and explain why the function is or is not a solution.

**D2.\*** I can apply Euler's Method to generate an approximate solution to an initial value problem and explain the result's meaning in context.

**D3.\*** I can express real world situations as differential equations, determine any stable or unstable equilibrium solutions, and explain the significance of the equilibrium solutions in context.

### Taylor Polynomials and Series

**T1.** Given appropriate information about a function, I can find its Taylor polynomials at a given center *a*.

**T2.** I can determine whether or not an infinite series is geometric and, if so (and it converges), find its sum.

**T3.** I can use the Taylor series of one or more familiar functions to find the Taylor series for a related function.

## University Core Statement

The University of Portland offers a liberal arts Core Curriculum with a vision of students acquiring knowledge, skills, and values that will prepare you to respond to the needs of the world and its human family, while having a foundation of multiple lenses to address enduring questions of human concern. The University Core Curriculum strives to achieve this vision by cultivating six habits of heart and mind in all graduates regardless of major.

As a priority for this Core class, our focus is the \`\`scientific and quantitative literacy and problem solving'' habit. As part of developing that habit this course will prioritize students learning to employ mathematical and statistical skills to explore and make sense of data. Toward this end, as one specific Core learning outcome for this class, the expectation is that students who complete this course will be able to use the tools of differential and integral calculus to solve complex problems and effectively communicate solutions in written form.
