---
title: "General Course Information"
format:
  html: default
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

This semester, I have two sections of MTH 202. It's helpful (especially early in the semester) if you you specify your section in any communications with me. You should also include that information on any papers that you hand in.

-   **Section A**
    -   MWRF 8:10-9:35, DB 230
-   **Section B**
    -   MWF 11:25-12:20, Franz 234\
        R 12:55-1:50, Franz 026

### Instructor

Chris Hallstrom, PhD <br> (he/him)

Students sometimes ask how they should address me. While I won't be offended if you use my first name, I know that many students aren't comfortable doing so. I also recognize that I have some amount of privilege in this regard and that many of my colleagues would find it rude or presumptuous to use first names. In solidarity with them I'd suggest that you call me "Dr. Hallstrom" or "Prof. Hallstrom".

-   [Gender Bias in Course Evaluations](//https://www.insidehighered.com/news/2018/03/14/study-says-students-rate-men-more-highly-women-even-when-theyre-teaching-identical)
-   ["My First Name"](https://docs.google.com/document/d/1bGDW6BChhG-DvPlli__AoJJQUf0TfFrL9tFEJNgTvvs/edit?usp=sharing) by Susan Harlan, *The South Carolina Review*, 20217 (49.2)
-   ["Tenure, She Wrote"](https://tenureshewrote.wordpress.com/2014/03/11/feel-ree-to-call-me-dr/)
-   [What Should I Call My Professor Flow Chart](https://i1.wp.com/www.unwrittenhistories.com/wp-content/uploads/2016/09/Flow-Chart-2.jpg)

### Email

[hallstro\@up.edu](//mailto:hallstro@up.edu)

If you send me email after 5pm, there's a good chance that I will not see it until the following morning. Similarly, I don't check my email regularly on weekends so you might not get a reply until Monday. I will do my best to respond as soon as I am able, but if you haven't heard back from me in a timely manner - please feel free to follow-up!

### Office

Buckley Center 270m -- located on the second floor of the NW wing of Buckley Center (BC). While I do have specific times set aside for [drop-in hours](support.qmd#drop-in-hours), you are always welcome to stop by at anytime!

## Course Materials

### Textbook

We will be using the open source textbook [Active Caclulus Single Variable, 2nd Edition](https://activecalculus.org/acs2e/) by Matthew Boelkins, et al. 2025. This is freely available in both online (HTML) and PDF versions through these links:

-   [Online Version](https://activecalculus.org/single2e/frontmatter.html)
-   [PDF Version](https://activecalculus.org/wp-content/uploads/2025/08/acs2e-8-7-25.pdf)

I recommend that you use the Online version as it will give you access to interactive problems embedded in the text.\
Note that the text covers both semesters of Calculus -- our class will focus on Chapters 5-8.

While a print version of the 2nd edition is not yet available, for Calc II the only difference betweeen the 1st and 2nd editions is Chapter 8, so if you really want a print version, the 1st edition would be fine for Chapters 5-7. To be clear -- you do not need a print copy - I mention it just because some students like to have a hard copy of the text. You can order a print version [here](https://www.amazon.com/Active-Calculus-2018-Single-Variable/dp/1724458329/) for about \$25 which covers the cost of printing.

### Workbook

All of the activities from the textbook can also be found bundled in an Activites Workbook for chapters 5-8:

`[AW]`: [Active Calculus Activities Workbook, chs 5-8, 2nd Ed.](https://activecalculus.org/wp-content/uploads/2025/08/acs2e-activity-workbook-58-8-7-25.pdf)

These activities are the same as what you'll find in the textbook, but are formatted with additional white space to make it easier to write and organize your work. It's not at all necessary that you print these out yourself -- but they're here if you think that might be useful.

All additional handouts or course materials will be posted on our class [Moodle](https://learning.up.edu) page. I will also regularly post a summary of our class activities so if you ever miss class for any reason, you can check there to see what you missed.

### Technology

I expect that eveyone has access to a desktop computer, laptop, or tablet device. We will make extensive use of the online graphing tool [Desmos](https://www.desmos.com/calculator) so if you don't already have a free Desmos account, I suggest that you do that so. It's not necessary to have an account, but it does allow you to save your work. In class, we will often be working in small groups so it's not necessary for everyone to bring a device to class, but you'll want to be able to use it outside of class.

If you need any assistance getting access to technology, please let me know!

### AI Policy

### Collaboration

Unless otherwise instructed, I encourage you to work together with classmates on homework or other, although any work that you hand in (unless it's specified as a group assignment) should be your own.

### Online resources (including AI)

I am well aware that there are many online tools that can do many calculations for you. We will talk extensively about when it's appropriate to use these tools and when it is not. If you do use any online resources, you should absolutely document that. Be specific about what tools you use and how you use them.

### Late work & extensions {#sec-late-work-extensions}

Due dates for assignments are there to give you structure and to help you keep up with the course material. They also help me provide you with feedback in a timely manner. That said, I understand that things come up periodically that can make it difficult to complete an assignment by the deadline. Life happens!

If something comes up that prevents you from completing an assignment by the posted due date, just send me email and let me know when I can expect your work. You do not need to provide an explanation. In general, I will expect to receive your work within **one week**.

There are, however, two **hard deadlines** to be aware of: Oct. 11th (Friday before Fall break) and Dec. 6th (last day of classes). Except in unusual circumstances or by prior arrangement, I will not accept work after those dates.

### Important dates {#sec-important-dates}

-   **Mon, Aug. 25:** Classes begin
-   **Fri, Aug. 29:** Last day to add/drop
-   **Mon, Sep. 1:** Labor Day -- classes in session, offices closed
-   **Mon-Fri, Oct. 13-17**: Fall Break
-   **Mon, Nov 24:** Last day to Withdraw
-   **Thur-Fri, Nov 27-28:** Thanksgiving
-   **Fri, Dec 5**: Last day of classes
-   **Mon, Dec 8**: Section B final check-in, 1:30-3:30
-   **Tue, Dec 9**: Section A final check-in, 1:30-3:30
