---
title: "Grades"
format:
  html: 
    toc: true
    toc-expand: 2
    toc-title: "On this page"
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

> Extrinsic motivation, which includes a desire to get better grades, is not only different from, but often undermines, intrinsic motivation, a desire to learn for its own sake.
>
> ::: {style="text-align: right"}
> -- Alfie Kohn, ["The Case Against Grades"](https://www.alfiekohn.org/article/case-grades/)
> :::

Grades, as they are traditionally thought of, are inherently imprecise and don't represent a full picture of your growth and learning over the course of a semester. Worse than that, research shows that grades undermine the learning process in several ways:

-   Grades tend to diminish interest in what you're learning.

-   Grades create a preference for the easiest task so that students tend to do what they need to get a certain grade, but no more.

-   Grades tend to reduce the quality of student thinking. The moment we ask \`\`**how** am I doing?'' we lose track of **what** we're doing.

Unfortunately, I am required to submit a grade for each student at the end of the semester -- but I will do what I can to de-emphasize the role of grades in this course so that as much as possible our focus is on learning.

## Feedback and Revisions {.unnumbered}

Your goal throughout the semester is to demonstrate your understanding of the course material and specifically our stated learning objectives through your work. Rather than giving you marks on individual assignments, I will instead give you written feedback to let you know how I see your understanding reflected in your work. After addressing that feedback, you're welcome to resubmit for further feedback if needed.

Throughout the semester, I will also periodically ask you to reflect carefully on your work and to self-evaluate your progress. The primary pieces of evidence of your learning will be the labs and the projects, but you're welcome to include any other work in these reflections that you feel demonstrates your learning.

## Collaborative Grading {.unnumbered}

At mid-semester and again at the end of the semester, we will compare notes about where you are in your learning. I'll ask you to present evidence of your learning and in this way, we will determine your your grade collaboratively.

The intention here is to help you focus on learning in a way that is more organic, as opposed to simply working as you think you're expected to. If this process causes more anxiety than it alleviates, please see me at any point to confer about your progress in the course -- I'm always happy to talk with you about your learning!

## Engagement {.unnumbered}

Although your course grade will primarily be based on your **understanding** of course content and not on course engagement, in my experience these typically go hand in hand. So while engagement in the course is not itself evidence of understanding, it does usually help us achieve that goal.

Here are some ways that you can engage with the class:

-   Attend class regularly
-   Complete assigned problems before class so you're prepared to engage with that day's material.
-   Contribute to in-class group work including Application Exercises.
-   Complete weekly engagement reports
-   Complete periodic check-ins
-   Come to drop-in hours to ask questions
-   Complete labs on time -- and asking for help when needed.
-   Completing projects on time -- and asking for help when needed.

## Grade Guidelines {.unnumbered}

Here are some qualitative descriptions that I find helpful in thinking about student grades. You might find them helpful as well.

A

:   This grade generally indicates superior work that demonstrates a deep understanding of the material such that you could apply the material in unfamiliar or especially complex situations. You should should consistently demonstrate this deep understanding of the material using a wide variety of methods described above. This grade likely includes:

-   demonstrating **significant** course engagement, including homework, as evidenced in weekly engagement reports and AEs
-   successfully completing **all** lab assignments
-   successfully completing **both** projects

B

:   This grade indicates good work that is eminently satisfactory. You should be able to use and extend this knowledge in many situations although you might have difficulty with particularly challenging or unfamilar problems. You should consistently demonstrate your understanding of the material using some of the methods described above. This grade likely includes

-   demonstrating **many** elements of course engagement as evidenced in weekly engagement reports and AEs
-   completing **most** lab assignments
-   completing **both** projects

C

:   This grade indicates competent work that demonstrates an basic understanding of the course material. You should be able to handle most of the more straightforward problems encountered but might struggle with more challenging problems. You might consistently meet only a few of the criteria listed above or else meet several criteria but less often. This grade likely includes

-   demonstrating **some** elements of course engagement as evidence in weekly engagement reports and AEs
-   completing **some** lab assignments
-   attempting at least **one** project

D/F

:   These grades represent a fundamental breakdown of expectations. A D represents a meaningful but unsuccessful attempt at earning a C or above. An F represents such a severe lack of engagement, effort, or understanding that there is no evidence of meaningful progress.

+/-

:   In discussing your course grade together, we may opt to add a modifier to your grade.

-   A $\mathbf{-}$ modifier might be added to your grade if you've met the standards for a particular grade with the exception of one element (engagement, labs, or projects e.g.)

-   A $\mathbf{+}$ modifier might be added to your grade if you've met the standards for a particular grade **and** you've met one of the elements for a higher grade.
